sudo userdel octavia.blake
sudo userdel bellamy.blake
sudo userdel abigail.griffin
sudo userdel finn.collins
sudo userdel jasper.jordan
sudo userdel raven.reyes
sudo userdel monty.green
sudo userdel clarke.griffin
sudo userdel marcus.jane
sudo userdel john.murphy
sudo userdel wells.jaha
sudo userdel maddy.griffin
